name: Build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        msystem: msys
        update: true
        install: >-
          make
          mingw-w64-x86_64-toolchain
          mingw-w64-i686-toolchain
    - name: Build64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        set MSYSTEM=MINGW64
        msys2 -c "mkdir -p release/x64"
        msys2 -c "make ARCH=x64"
        msys2 -c "cp out/swiss.exe release/x64"
        set MSYSTEM=MINGW32
        msys2 -c "mkdir -p release/x86"
        msys2 -c "make ARCH=x86"
        msys2 -c "cp out/swiss.exe release/x86"
        msys2 -c "cp README.md release/README.md"
        msys2 -c "cp LICENSE release/LICENSE"

    - uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'swiss.zip'
        directory: 'release'
        path: '.'

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          swiss.zip
