name: Build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: >-
          make
          mingw-w64-x86_64-toolchain
          mingw-w64-i686-toolchain
    - name: Build64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        export PATH=/mingw64/bin:$PATH
        mkdir -p release/x64
        make ARCH=x64
        cp out/swiss.exe release/x64

    - name: Build32
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        export PATH=/mingw32/bin:$PATH
        mkdir -p release/x86
        make ARCH=x86
        cp out/swiss.exe release/x86
        cp README.md release/README.md
        cp LICENSE release/LICENSE

    - uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'swiss.zip'
        directory: 'release'
        path: '.'

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          swiss.zip
